keys:
  - &host_cloud age16ptmj3r8r2xuz0tkztftt5f65e2764gk7dt9kqz3427xr0s5cd0q3le0a8
  - &admin_ayats age12ew7ztetf7ju00ssp6673jgqpnrpa6hnvm58s92v3clk4msxtfcq7knj6j
creation_rules:
  - path_regex: .secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *host_cloud
      - *admin_ayats
