name: "Flake update"

on:
  workflow_dispatch:
  schedule:
  - cron: "*-*-01 00:00:00"

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20220122_c9a4ddb/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - run: nix flake update
    - name: Create Pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        title: "GitHub actions: automatic flake update"
        commit-message: "github actions: flake update"
        branch: update
        delete-branch: true
